import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'İmza Pratik Web',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       <Head>
        <title>
          İmza Pratik
        </title>
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
      </Head>

      <body className={inter.className}>{children}</body>
    </html>
  )
}
